server:
  port: 8093

app:
  jwt:
    secret: DianpingJwtSecretKey-ChangeMe-2026
    expire-minutes: 120
    refresh-expire-days: 7

spring:
  data:
    redis:
      host: 192.168.145.128
      port: 6379
      password: 123456
  datasource:
    url: jdbc:mysql://localhost:3306/dianping_merchant?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-init-sql: SET NAMES utf8mb4

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
